### ISSUE TITLE
Turbolinks built-in progressbar instead of Nprogress

### ISSUE THREAD

**Issue by siegy22** [b1nary/Hackidihack#1]
What about using Turbolinks built-in progressbar? :grin:

See [this](http://stackoverflow.com/questions/36193256/turbolinks-5-show-progress-bar) how to.

**Comment by b1nary** [comment]
Good guy @siegy22 still reading the relevant changelogs ;)

Did not know that actually, so thanks for the report, i'll look into it

**Comment by b1nary** [comment]
Ok takes a bit to much configuration to get it work like i want it, thanks anyway. I was not aware this features is available for a few versions now.

**Comment by siegy22** [comment]
I think `Turbolinks.ProgressBar.enable();` will do the trick
